# Generated by Django 5.0 on 2023-12-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adjacent_district",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Соседний район",
                "verbose_name_plural": "Соседние районы",
                "db_table": "adjacent_districts",
                "db_table_comment": "Table of adjacent areas",
                "ordering": ["main_district", "neighboring_district"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название категории",
                        max_length=100,
                        verbose_name="Наименование категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "db_table": "categorys",
                "db_table_comment": "Table of categorys",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название изображения",
                        max_length=100,
                        verbose_name="Наименование изображения",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Укажите путь до файла изображения",
                        upload_to="",
                        verbose_name="Путь до файла изображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
                "db_table": "pictures",
                "db_table_comment": "Table of pictures",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название района",
                        max_length=200,
                        verbose_name="Наименование района",
                    ),
                ),
                (
                    "adjacent_district",
                    models.ManyToManyField(
                        blank=True,
                        through="wiki.Adjacent_district",
                        to="wiki.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Район",
                "verbose_name_plural": "Районы",
                "db_table": "districts",
                "db_table_comment": "Table of city districts",
                "ordering": ["-date_created"],
            },
        ),
        migrations.AddField(
            model_name="adjacent_district",
            name="main_district",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_district",
                to="wiki.district",
            ),
        ),
        migrations.AddField(
            model_name="adjacent_district",
            name="neighboring_district",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="neighboring_district",
                to="wiki.district",
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название локации",
                        max_length=200,
                        verbose_name="Наименование локации",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Введите описание локации",
                        max_length=5000,
                        verbose_name="Описание локации",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wiki.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wiki.picture",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
                "db_table": "locations",
                "db_table_comment": "Table of interesting places",
                "ordering": ["-date_created"],
            },
        ),
    ]
