# Generated by Django 5.0 on 2023-12-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="category",
            table_comment="Table of categoryes",
        ),
        migrations.AlterField(
            model_name="location",
            name="picture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wiki.district",
                verbose_name="Район",
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="categoryes",
        ),
    ]
