# Generated by Django 5.0 on 2023-12-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wiki",
            "0002_alter_category_table_comment_alter_location_picture_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wiki.district",
                verbose_name="Район",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="picture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wiki.picture",
                verbose_name="Изображение",
            ),
        ),
    ]
