# Generated by Django 5.0 on 2023-12-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0003_location_district_alter_location_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="picture",
        ),
        migrations.AddField(
            model_name="picture",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picture",
                to="wiki.location",
                verbose_name="Изображение",
            ),
        ),
    ]
